### ISSUE TITLE
v0.4 Milestone

### ISSUE THREAD

**Issue by geofmureithi** [geofmureithi/apalis#12]
- [x] Push job need to return id.
- [ ] Add functionality to push multiple jobs.
- [x] Add documentation on job function structure.

**Comment by geofmureithi** [comment]
@autotaker Feel free to suggest some more functionality we can add as we head to V0.4

**Comment by rustdreamer** [comment]
Is there an estimated time for version 0.4? Is there anything I can do for you?

**Comment by geofmureithi** [comment]
You could help with Redis integration tests 
https://github.com/geofmureithi/apalis/issues/9

**Comment by autotaker** [comment]
>  Push job need to return id.

👍

**Comment by geofmureithi** [comment]
I am thinking we can have apalis-cli for 0.4 which would allow spawning commands running them as child processes. 
This would allow config via toml where one can also set some layers eg retries, concurrency, sentry etc

**Comment by AzHicham** [comment]
Hello :) 
Another cool feature would be task cancellation. 
Since tasks are created by spawning` tokio::task`, we can easily use `JoinHandle::abort`.

Unfortunately this does not work if task does not call async operation. 
One possibility I guess would be to have either an Atomic Status or channel Receiver in JobContext to cancel the blocking task.

```
async fn long_blocking_task(job: Input, ctx: JobContext) -> impl IntoJobResponse {
    let status: Arc<Mutex<Status>> = ctx.status;
    let check_for_cancel =  || { status.read() == Status::Cancel };
    // let check_for_cancel =  || { ctx.rx_cancel.try_recv().is_ok() };

    small_compute1();
    check_for_cancel(); // if true exit immediately and return JobResponse::Cancel;
    small_compute2();
    check_for_cancel();
    small_computeN();
    check_for_cancel();
}
```

**Comment by geofmureithi** [comment]
@AzHicham True, we could add this functionality to context. :)
