### ISSUE TITLE
Integration tests for each backend

### ISSUE THREAD

**Issue by autotaker** [geofmureithi/apalis#9]
Currently integrations tests are running on CI only for MySQL backend. 

Let's add integration tests for the following backends 

- [x] Mysql by @autotaker (added by #6)
- [x] Redis by @geofmureithi (added by #27)
- [x] Sqlite by @geofmureithi (added by #13)
- [x] Postgres by @autotaker (added by #11)

Let's strive to have different pull requests for each storage. This will help in collaboration.
Also before starting on any backend, please add a comment and assigned.

**Comment by geofmureithi** [comment]
Awesome.

**Comment by autotaker** [comment]
I'll take on the Postgres part.

**Comment by autotaker** [comment]
@geofmureithi 
By adding tests, I found a bug with killing jobs, and created a PR: #10.
I'd appreciate if you could review it.

**Comment by geofmureithi** [comment]
@autotaker on it!

**Comment by autotaker** [comment]
@geofmureithi 
Thank you for merging #10!

Now, PR to adding Postgres integration test is ready! #11

**Comment by geofmureithi** [comment]
@autotaker What do you think about sqlite tests failing. I am unsure why 😅

**Comment by autotaker** [comment]
@geofmureithi 
about test failures:

- test_consume_last_pushed_job:
  - Because `lock_at` is not updated by `fetch_next`
     https://github.com/geofmureithi/apalis/blob/2fc757bbaf9b889aa473fb875e8bd65dbdf22b53/packages/apalis-sql/src/sqlite.rs#L116 
- test_heartbeat_renqueueorphaned_pulse_last_seen_6min:
  - Because type inconsistency of `last_seen` (sqlite does not check types of columns)
  - In `keep_alive_at`: `last_seen` in date time format (like `2022-10-03 00:12:34`)
  - In `keep_alive`: `Utc::now().timestamp()` in timestamp format (like `1664765208`)

**Comment by autotaker** [comment]
@geofmureithi 
I've add more tests for MySQL backend: #15 
Could you review this PR?

Thanks in advance.

**Comment by geofmureithi** [comment]
@autotaker You are the MVP!
